name: Java CI with Maven

on: workflow_dispatch
  # push:
  #   branches: [ "main", "master" ]
  # pull_request:
  #   branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Fetch Secret from Azure Key Vault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "your-key-vault-name"
        secrets: "SauceDemoPassword"
      id: myGetSecrets
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Install Chrome Browser
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Build with Maven
      run: mvn clean verify
      env:
        SAUCEDEMO_PASSWORD: ${{ steps.myGetSecrets.outputs.SauceDemoPassword }}
    
    - name: Run Tests
      run: mvn test
      env:
        SAUCEDEMOS_PASSWORD: ${{ steps.myGetSecrets.outputs.SauceDemoPassword }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: target/surefire-reports
